# This file is used to override the default Sentry configuration without
# having to specify the options on the command line.
#
# All configuration options in this file are optional, and will fall back
# to the default values that Sentry determines based on your `shard.yml`.
#
# Options passed through the command line will override these settings.

# The name of your application when displayed in log output. By default, this
# is the app name specified in `shard.yml`.
display_name: sentry

# Set this to `true` to show configuration information when starting Sentry.
info: true

colorize: false

play_audio: false

should_build: false

# The command used to compile the application, e.g. crystal
build_command: crystal

# Any additional arguments to pass to the build command.
build_args: build ./src/sentry_cli.cr -o ./bin/sentry

# The command used to run the compiled application.
run_command: ./bin/sentry

# Any additional arguments to pass to the run command.
run_args: -p 3288

run_shards_install: true

# The list of patterns of files for sentry to watch.
watch:
  - ./src/**/*.cr
  - ./src/**/*.ecr
